In [1]:
import pandas as pd
import numpy as np

In [2]:
movie = pd.read_csv('imdb-top-1000.csv')
movie.head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [7]:
## finding director with  most popularity,

movie.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [9]:
# find the highest rated movie in each genre,

movie.groupby(['Series_Title','Genre'])['IMDB_Rating'].max().sort_values(ascending=False)

Series_Title              Genre
The Shawshank Redemption  Drama        9.3
The Godfather             Crime        9.2
The Godfather: Part II    Crime        9.0
The Dark Knight           Action       9.0
12 Angry Men              Crime        9.0
                                      ...
Watership Down            Animation    7.6
300                       Action       7.6
28 Days Later...          Drama        7.6
When Harry Met Sally...   Comedy       7.6
25th Hour                 Drama        7.6
Name: IMDB_Rating, Length: 999, dtype: float64

In [17]:
## find number of movies done by each actors,

movie.groupby('Star1')['Series_Title'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

In [22]:
## we can also find that after grouping how many numbers of group is created,

len(movie.groupby('Genre'))

14

In [21]:
movie['Genre'].nunique()

14

In [5]:
# finding the number of movies that starts with letter A for each group,

genres = movie.groupby('Genre')

def fin(group):
    return print(group['Series_Title'].str.startswith('A').sum())

genres.apply(fin)

10
2
2
9
14
4
21
0
0
0
1
0
0
0

C:\Users\MAHAKAAL\AppData\Local\Temp\ipykernel_11040\3844077775.py:8: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(fin)

Empty DataFrame
Columns: []
Index: []