In [1]:
import pandas as pd
import numpy as np

In [2]:
courses = pd.read_csv('courses.csv')
bolly = pd.read_csv('bollywood.csv')
deli = pd.read_csv('deliveries.csv')
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')
students = pd.read_csv('students.csv')

In [3]:
nov.head(2)

   student_id  course_id
0          23          1
1          15          5

In [4]:
courses.head(2)

   course_id course_name  price
0          1      python   2499
1          2         sql   3499

In [5]:
deli.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [6]:
dec.head(2)

   student_id  course_id
0           3          5
1          16          7

In [7]:
students.head(2)

   student_id           name  partner
0           1  Kailash Harjo       23
1           2    Esha Butala        1

In [8]:
bolly.head(2)

                      movie           lead
0  Uri: The Surgical Strike  Vicky Kaushal
1             Battalion 609    Vicky Ahuja

In [4]:
##

cc = pd.merge(courses,nov,on='course_id',how='left')
cc['course_name'].value_counts()

course_name
python              6
data analysis       4
machine learning    3
power bi            3
ms sxcel            2
tableau             2
pyspark             2
sql                 1
pandas              1
plotly              1
Numpy               1
C++                 1
Name: count, dtype: int64